package com.aiworkflow.workmanagement.orchestration.node.template;

import com.aiworkflow.workmanagement.orchestration.config.OrchestrationConfig;
import com.aiworkflow.workmanagement.orchestration.domain.OrchestrationState;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

/**
 * Template node for research operations.
 * <p>
 * Generates deterministic research findings based on story metadata.
 * This node simulates what a researcher agent would produce when investigating
 * a story's requirements and technical context.
 *
 * <h2>Output Artifact</h2>
 * <ul>
 *   <li><strong>Name</strong>: research-findings</li>
 *   <li><strong>Role</strong>: researcher</li>
 *   <li><strong>Format</strong>: Markdown with sections for context, findings, recommendations</li>
 * </ul>
 *
 * <h2>Template Structure</h2>
 * <pre>
 * # Research Findings: {story title}
 *
 * ## Context
 * {work intent and story description}
 *
 * ## Key Findings
 * - Finding 1 (based on story metadata)
 * - Finding 2
 * - Finding 3
 *
 * ## Recommendations
 * - Recommendation 1
 * - Recommendation 2
 *
 * ## Next Steps
 * - Suggested next actions
 * </pre>
 */
@Component
@ConditionalOnProperty(name = "orchestration.execution-mode", havingValue = "template")
public class ResearchTemplateNode extends AbstractTemplateNodeAction {

    public ResearchTemplateNode(OrchestrationConfig config) {
        super(config);
    }

    @Override
    protected String getNodeName() {
        return "research";
    }

    @Override
    protected String getArtifactName() {
        return "research-findings";
    }

    @Override
    protected String getRoleName() {
        return "researcher";
    }

    @Override
    protected String generateContent(OrchestrationState state) {
        String storyTitle = getStoryTitle(state);
        String workIntent = getWorkIntent(state);
        String description = getStoryDescription(state);

        StringBuilder content = new StringBuilder();
        content.append("# Research Findings: ").append(storyTitle).append("\n\n");

        // Context section
        content.append("## Context\n\n");
        if (!workIntent.isEmpty()) {
            content.append("**Work Intent**: ").append(workIntent).append("\n\n");
        }
        if (!description.isEmpty()) {
            content.append("**Story Description**: ").append(description).append("\n\n");
        }

        // Key findings section
        content.append("## Key Findings\n\n");
        content.append("Based on the story requirements, the following key findings have been identified:\n\n");
        content.append("- **Scope Analysis**: The story appears to be well-defined with clear objectives\n");
        content.append("- **Technical Feasibility**: Implementation appears feasible with current technology stack\n");
        content.append("- **Dependencies**: No major external dependencies identified at this stage\n");
        content.append("- **Complexity Assessment**: Medium complexity, suitable for iterative development\n\n");

        // Recommendations section
        content.append("## Recommendations\n\n");
        content.append("1. **Approach**: Break down into smaller, testable increments\n");
        content.append("2. **Architecture**: Follow existing patterns in the codebase\n");
        content.append("3. **Testing**: Implement comprehensive unit and integration tests\n");
        content.append("4. **Documentation**: Update relevant documentation as work progresses\n\n");

        // Next steps section
        content.append("## Next Steps\n\n");
        content.append("- Create detailed task breakdown\n");
        content.append("- Identify specific files and components to modify\n");
        content.append("- Define acceptance criteria for each task\n");
        content.append("- Estimate effort and prioritize work\n\n");

        // Metadata footer
        content.append("---\n");
        content.append("*Generated by: Template Research Node*\n");

        return content.toString();
    }
}
